### ISSUE TITLE
[BUG] Crash while generating structure

### ISSUE THREAD

**Issue by JustinHuPrime** [ThePansmith/CABIN#109]
**Describe the bug**
While exploring the world, generating new chunks, the game freezes as it tries to generate a structure

**To Reproduce**
1. Open [world file](https://zootron-public-drive.s3.ca-central-1.amazonaws.com/world-1.zip)
2. Head north
3. Experience server crash; client will freeze

**Additional context**
See also crash log attached at [crash-2024-09-07_16.18.37-server.txt](https://github.com/user-attachments/files/16920136/crash-2024-09-07_16.18.37-server.txt)

**Comment by Buduf** [comment]
I had this same issue in my world.

It happens when some other structure tries to generate on top of a crystal harvester structure. This structure has some Create blocks, which causes the crash when the worldgen is trying to replace it.

So I removed the structure by deleting `kubejs/data/cabin/worldgen/structure_set/crystal_harvester.json`. You might have to regenerate the world or delete that area.

**Comment by cubebotfan** [comment]
This is an issue with create tanks being overridden by structures. The crash is caused an issue with Create itself so there isn't much we can do unless Create gets updated to fix it.

At first I thought this was a rare crash but it seems to be happening to more and more people now. New update, I'll remove all tanks from structures until this bug gets patched.

For now you can prevent the crash by deleting the file minecraft\kubejs\data\cabin\worldgen\structure_set\crystal_harvester.json so that the structure doesn generate.

**Comment by cubebotfan** [comment]
Hopefully fixed in 7eb4e08
