### ISSUE TITLE
[BUG] Windmill Frame into Windmill Sail recipe is broken

### ISSUE THREAD

**Issue by ssspons** [ThePansmith/CABIN#55]
**Describe the bug**
The recipe is missing, only a couple of tags show up.

**To Reproduce**
1. Install the newest CABIN version
2. Look up Windmill Frames
3. Press 'U'
4. See broken recipe

**Expected behavior**
Working recipe.

**Screenshots**
[Screenshot.
](https://i.imgur.com/fJribNu.png)

**Comment by cubebotfan** [comment]
I'll look into this

**Comment by cubebotfan** [comment]
Sorry for lying 2 weeks ago. Now that I've actually looked into it I can see that the default windmill sail recipe has been removed and replaced. I'm assuming the issue is that the kubejs script removes **All** windmill sail recipes instead of just removing one of them.
![image](https://github.com/ThePansmith/CABIN/assets/150861277/2e3b7cd0-0383-42b5-833c-c9eae7e01cc7)
